"""Agregar columna is_visible a Comentario

Revision ID: ae5c642cd1a0
Revises: cc79e349e717
Create Date: 2025-11-05 14:43:53.437209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5c642cd1a0'
down_revision = 'cc79e349e717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
